[workspace]
resolver = "2"
members = ["badge_net", "server_net"]

[patch.crates-io]
embedded-tls = { git = "https://github.com/drogue-iot/embedded-tls.git", rev = "f788e02deda787542a079cbddb5226af37aa818c" }
