services:
  webbadge:
    image: aughey/webbadge:latest
    expose:
      - 3000
      - 4443
  nginx:
    image: nginx
    volumes:
      - /tmp/keys:/keys
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
      - "12345:12345"
